### ISSUE TITLE
Failing tests in master

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tilelive-s3#41]
The last commit 4 months ago to travis passed (https://travis-ci.org/mapbox/tilelive-s3/builds), but master consistently fails its tests now:

```
# getGeocoderData
ok 108 null
not ok 109 should be equal
  ---
    operator: equal
    expected: 0
    actual:   3891
  ...
# getGeocoderData (prefixed source)
ok 110 null
not ok 111 should be equal
  ---
    operator: equal
    expected: 0
    actual:   3891
  ...
# getGeocoderData (no geocoder)
ok 112 undefined
ok 113 should be equal
# getIndexableDocs
/Users/travis/build/mapbox/tilelive-s3/node_modules/tape/index.js:75
        throw err
              ^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/travis/build/mapbox/tilelive-s3/lib/index.js:512:34
    at /Users/travis/build/mapbox/tilelive-s3/lib/index.js:457:17
    at Inflate.onEnd (zlib.js:167:5)
    at Inflate.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)
```

**Comment by yhahn** [comment]
On it -- looks like we moved the location of expected fixtures on S3 to consolidate some buckets.

**Comment by springmeyer** [comment]
stale, closing.
